### ISSUE TITLE
LSOA Vis Discussion

### ISSUE THREAD

**Issue by mem48** [npct/pct-lsoa-vis#2]
A place to discuss visualization issues for the LSOA rasters:

To get started:

- [ ] Colour Scheme for Rasters

- [ ] Where to set cutoffs, max, min between different colours etc

**Comment by mem48** [comment]
Here is a example dataset from london.

https://github.com/npct/pct-lsoa/releases/tag/0.1.1

Download and unzip then open in ArcGIS, QGIS etc it will not show up in normal image editors

**Comment by mem48** [comment]
Some quick visualisation examples. Using the Census 2011 4p lines

First London using red-blue colour scheme, the bands automatically assigned by ArcGIS using the Jenks method
![jenks](https://cloud.githubusercontent.com/assets/15819577/22374482/413628b8-e49e-11e6-9084-d5395299aee7.png)

Looks ok, but in a quieter place (Canterbury)

![jenks2](https://cloud.githubusercontent.com/assets/15819577/22374886/e3721244-e49f-11e6-917e-282637b1a0a5.png)

The resutls are quite flat.

To address this I changed the colours and the bands, putting more bands low down but using softer colours that visually don't "pop". Then darker blues that make the key roads stand out. Finally a special purple for the really key roads that only appear in major cities.

![mal1](https://cloud.githubusercontent.com/assets/15819577/22375008/53d7585a-e4a0-11e6-8814-9d19c5bac104.png)

And in Canterbury

![mal2](https://cloud.githubusercontent.com/assets/15819577/22375023/5d5ee4ec-e4a0-11e6-9288-053813ceabc8.png)

**Comment by AnnaGoodman1** [comment]
Thanks @mem48.  I agree that the 2nd raster  looks better in Canterbury, thanks. 2 questions
a) is it colour-blind friendly?
b) would it be possible to have a different colour for either the purple for the highest category, or for the pink for the lowest? They are visually pretty similar which is not ideal, esp as you do see both in the same image (e.g. in the London map).  For example, could the lowest pink colour be replaced by a light grey?

**Comment by Robinlovelace** [comment]
For the second one is better but neither are ideal. The second looks cool but there's too much going all those colors. Therefore I think something like the second (with 3 colors ) but with grey at the bottom, an MSOA-like blue for the mid and then something more racy (e.g. purple) for the hottest colors would be best for me.

**Comment by mem48** [comment]
A slightly tweaked version of my last post:

Replaced 1-5, 6-10 with a single 1-10 band and make it grey.

![mal3](https://cloud.githubusercontent.com/assets/15819577/22600512/bef2b494-ea32-11e6-8406-881a49afe5d4.png)

![mal4](https://cloud.githubusercontent.com/assets/15819577/22600515/c35d5b24-ea32-11e6-948e-7d0c217d364b.png)

**Comment by mem48** [comment]
Alternatively we could offer a sperate version that only highlighted the core network

![mal4](https://cloud.githubusercontent.com/assets/15819577/22600756/dcad048e-ea33-11e6-9afd-6988133ecb01.png)

**Comment by Robinlovelace** [comment]
I like this one lots. Advantages:

- It's more consistent with the msoa rnet.
- It's definitely colourblind friendly
- Will reduce confusion when the business of all the other layers are in there

Only changes I'd add: make the scales continuous (gdal will do that automatically) and use transparency instead of or as well as the grey lower value. The relevant 'number matrix' to edit magically is here - will be interested to see what incantation generates the right result on that front (heads up wizard @nikolai-b): https://github.com/npct/pct-lsoa-vis/blob/master/generate/colour.txt

**Comment by AnnaGoodman1** [comment]
This is looking very good.  I'm happy with the colour scheme, I think seeing LSOA in situ raises a couple of other issues which I will raise on the new thread that Nikolai has made at https://github.com/npct/pct-shiny/issues/523

**Comment by Robinlovelace** [comment]
I'm also happy with this - closing for now as everyone I've spoke to seems to be happy with this and no-one seems to object. Summary: go with it @nikolai-b from my perspective unless you hear otherwise by the end of the day.
